#!/usr/bin/env python3
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / '.env'

MD_PATH = Path(r"c:\Users\smart\Downloads\5cypress-marketing-team\5cypress-marketing-team\output\medsync-solutions\strategy-brief-2026-02.md")
PDF_OUT = MD_PATH.with_suffix('.pdf')
TO_ADDRESS = 'jimmy@nexairi.com'
FROM_ADDRESS = None


def load_env(path):
    env = {}
    if not path.exists():
        return env
    for line in path.read_text().splitlines():
        line=line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        k,v=line.split('=',1)
        env[k.strip()]=v.strip().strip('"')
    return env


def md_to_text(md):
    # Very small markdown-to-text converter
    # Replace headings and lists simply
    txt = md
    txt = re.sub(r"^#\s+", "", txt, flags=re.M)
    txt = re.sub(r"^##\s+", "", txt, flags=re.M)
    txt = re.sub(r"\*\*(.*?)\*\*", r"\1", txt)
    txt = re.sub(r"\*(.*?)\*", r"\1", txt)
    txt = re.sub(r"\[(.*?)\]\((.*?)\)", r"\1 (\2)", txt)
    txt = re.sub(r"^\s*[-*+]\s+", " - ", txt, flags=re.M)
    return txt


def make_pdf(text, out_path):
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    from reportlab.lib.units import inch

    doc = SimpleDocTemplate(str(out_path), pagesize=letter,
                            rightMargin=72,leftMargin=72,
                            topMargin=72,bottomMargin=72)
    styles = getSampleStyleSheet()
    normal = styles['Normal']
    normal.fontName = 'Helvetica'
    normal.fontSize = 10
    elems = []
    for para in text.split('\n\n'):
        p = Paragraph(para.replace('\n','<br />'), normal)
        elems.append(p)
        elems.append(Spacer(1, 6))
    doc.build(elems)


def send_email(smtp_host,smtp_port,secure,username,password,from_addr,to_addr,subject,body,attachment_path):
    import smtplib
    from email.message import EmailMessage
    msg = EmailMessage()
    msg['Subject'] = subject
    msg['From'] = from_addr
    msg['To'] = to_addr
    msg.set_content(body)
    with open(attachment_path,'rb') as f:
        data=f.read()
    msg.add_attachment(data, maintype='application', subtype='pdf', filename=Path(attachment_path).name)

    if secure:
        server = smtplib.SMTP_SSL(smtp_host, int(smtp_port), timeout=20)
    else:
        server = smtplib.SMTP(smtp_host, int(smtp_port), timeout=20)
        server.starttls()
    try:
        server.login(username, password)
        server.send_message(msg)
    finally:
        server.quit()


if __name__ == '__main__':
    env = load_env(ENV_PATH)
    # prefer explicit from; default to DEFAULT_FROM or nick
    FROM_ADDRESS = env.get('DEFAULT_FROM') or env.get('SENDER_DOMAIN') or 'nick@5cypress.com'

    # Prefer CYPRESS_ADMIN SMTP settings (5cypress domain) to send as nick@
    smtp_host = env.get('CYPRESS_ADMIN_SMTP_HOST') or env.get('SMTP_HOST')
    smtp_port = env.get('CYPRESS_ADMIN_SMTP_PORT') or env.get('SMTP_PORT') or '465'
    smtp_user = env.get('CYPRESS_ADMIN_SMTP_USER') or env.get('SMTP_USER')
    smtp_pass = env.get('CYPRESS_ADMIN_SMTP_PASS') or env.get('SMTP_PASS')
    smtp_secure = (env.get('CYPRESS_ADMIN_SMTP_SECURE') or env.get('SMTP_SECURE') or 'true').lower() in ('1','true','yes')

    if not MD_PATH.exists():
        print('ERROR: markdown file not found:', MD_PATH)
        sys.exit(2)

    md = MD_PATH.read_text(encoding='utf-8')
    text = md_to_text(md)
    print('Generating PDF to', PDF_OUT)
    make_pdf(text, PDF_OUT)
    print('PDF generated')

    if not smtp_host or not smtp_user or not smtp_pass:
        print('SMTP credentials missing; leaving PDF at', PDF_OUT)
        sys.exit(0)

    subject = 'Strategy Brief — MedSync Solutions'
    body = 'Attached: Strategy brief for MedSync Solutions (generated by 5 Cypress Automation).'
    print('Sending email via', smtp_host, 'as', smtp_user, 'From header:', FROM_ADDRESS)
    try:
        send_email(smtp_host, smtp_port, smtp_secure, smtp_user, smtp_pass, FROM_ADDRESS, TO_ADDRESS, subject, body, PDF_OUT)
        print('Email sent to', TO_ADDRESS)
    except Exception as e:
        print('Email failed:', e)
        sys.exit(3)
