#!/usr/bin/env python3
"""
stamp_skill_headers.py
Add a standardised metadata block to every SKILL.md that lacks one.

Safe to re-run — already-stamped files are left untouched.

Usage:
    python scripts/stamp_skill_headers.py           # stamp all
    python scripts/stamp_skill_headers.py --dry-run # preview only
"""

from __future__ import annotations

import argparse
import re
from datetime import date
from pathlib import Path

REPO_ROOT  = Path(__file__).resolve().parents[1]
SKILLS_DIR = REPO_ROOT / ".claude" / "skills"
TODAY      = date.today().isoformat()

# Re-use domain map from generate_skill_registry
DOMAIN_MAP: dict[str, str] = {
    "3d-web-experience":        "development",
    "api-scaffolding":          "development",
    "backend-development":      "development",
    "blockrun":                 "development",
    "code-documentation":       "development",
    "data-validation":          "development",
    "development":              "development",
    "exploratory-data-analysis":"development",
    "frontend-design":          "development",
    "mobile-design":            "development",
    "payment-processing":       "development",
    "python-development":       "development",
    "schema-markup":            "development",
    "senior-backend":           "development",
    "ui-design-system":         "development",
    "website-builder":          "development",
    "ab-test-setup":            "marketing",
    "analytics-tracking":       "marketing",
    "campaign-presenter":       "marketing",
    "competitor-alternatives":  "marketing",
    "content-strategy":         "marketing",
    "copy-editing":             "marketing",
    "copywriting":              "marketing",
    "data-analysis-reporting":  "marketing",
    "email-campaign":           "marketing",
    "email-sequence":           "marketing",
    "executing-marketing-campaigns": "marketing",
    "free-tool-strategy":       "marketing",
    "launch-strategy":          "marketing",
    "marketing-ideas":          "marketing",
    "marketing-psychology":     "marketing",
    "marketing-research-strategy": "marketing",
    "paid-ads":                 "marketing",
    "product-marketing-context":"marketing",
    "referral-program":         "marketing",
    "social-content":           "marketing",
    "social-media-content":     "marketing",
    "5-cypress-premium-seo":    "seo",
    "programmatic-seo":         "seo",
    "seo-audit":                "seo",
    "customer-sales":           "sales",
    "cto-advisor":              "sales",
    "game-changing-features":   "sales",
    "pricing-strategy":         "sales",
    "form-cro":                 "conversion",
    "onboarding-cro":           "conversion",
    "page-cro":                 "conversion",
    "paywall-upgrade-cro":      "conversion",
    "popup-cro":                "conversion",
    "signup-flow-cro":          "conversion",
}

MARKER = re.compile(r"<!--\s*skill_id\s*:", re.IGNORECASE)


def _make_header(skill_id: str) -> str:
    domain  = DOMAIN_MAP.get(skill_id, "other")
    return (
        f"\n<!-- SKILL METADATA\n"
        f"skill_id:  {skill_id}\n"
        f"version:   1.0.0\n"
        f"domain:    {domain}\n"
        f"reviewed:  {TODAY}\n"
        f"status:    READY\n"
        f"changelog:\n"
        f"  1.0.0 - Initial version stamp (auto-generated by stamp_skill_headers.py)\n"
        f"-->\n"
    )


def stamp(path: Path, dry_run: bool) -> bool:
    """Return True if the file was (or would be) modified."""
    text = path.read_text(encoding="utf-8", errors="replace")
    if MARKER.search(text):
        return False  # already stamped

    skill_id = path.parent.name

    # Insert header after the first heading line (# Title)
    lines = text.split("\n")
    insert_at = 0
    for i, line in enumerate(lines):
        if line.startswith("#"):
            insert_at = i + 1
            break

    header = _make_header(skill_id)
    lines.insert(insert_at, header)
    new_text = "\n".join(lines)

    if not dry_run:
        path.write_text(new_text, encoding="utf-8")
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    stamped   = []
    untouched = []

    for folder in sorted(SKILLS_DIR.iterdir()):
        if not folder.is_dir() or folder.name.startswith("_"):
            continue
        skill_md = folder / "SKILL.md"
        if not skill_md.exists():
            print(f"  SKIP  {folder.name}/ — no SKILL.md")
            continue
        modified = stamp(skill_md, dry_run=args.dry_run)
        if modified:
            stamped.append(folder.name)
        else:
            untouched.append(folder.name)

    label = "Would stamp" if args.dry_run else "Stamped"
    print(f"\n{label}: {len(stamped)} skill(s)")
    for s in stamped:
        print(f"  + {s}")
    print(f"Skipped (already versioned): {len(untouched)}")


if __name__ == "__main__":
    main()
